spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://@dpg-d7u7v1v7f7vs73eo5keg-a.oregon-postgres.render.com/veebipood_database_ahrh?sslmode=require
spring.datasource.username=veebipood_user
spring.datasource.password=0LbCNezUad7UJQjIfstPcFQeVbohrLg1
